//
//  main.cpp
//  Max substrings without overlap
//
//  Created by Giriraj Saigal on 03/10/21.
//

#include <iostream>
#include <cmath>
#include <vector>
#include <map>
#include <unordered_map>
#include <stack>
#include <queue>
#include <set>
using namespace std;

    
int findEnd(int st, string s, unordered_map<char, vector<int>> &mp) {
    int end = st;
    
    for(int i = st; i <= end; i++) {
        end = max(mp[s[i]][1], end);
        
        if(mp[s[i]][0] < st)
            return -1;
    }
    
    return end;
}

vector<string> maxNumOfSubstrings(string s) {
    unordered_map<char, vector<int>> mp;
    
    for(int i = 0; i < s.size(); i++){
        if(mp.count(s[i])) {
            mp[s[i]][1] = i;
        }else{
            mp[s[i]] = {i,i};
        }
    }
    
    int n = s.size();
    int subStringStart = -1;
    
    vector<string> ans;
    for(int i = 0; i < n; i++) {
        int subStringEnd = findEnd(i, s, mp);
        if(subStringEnd != -1) {
            if(subStringEnd > subStringStart) {
                ans.push_back("");
            }
            subStringStart = subStringEnd;
            ans[ans.size()-1] = s.substr(i,subStringStart-i+1);
        }
    }
    
    return ans;
}

int main(int argc, const char * argv[]) {
    maxNumOfSubstrings("wurdaucdslkzjfmmchqbijcbtkderocgqntlysufcyickscopmottmpcuuujxfbcnabsxbrzoiehbdgfvwivmkdauiounsnfycohuzheaxazlxxwzyaszhieyefptrehrijpvvhixidndcmhkzrsteeiqjhaegzawpzqcdbcddjedgnaszyysodjectaucbnzdslrlunhlvikcjbsezyuqwrlnrenevmjnhxyflnvtuheskmjxjxikwzobdmbknvsoutuezpqoddkrxyjvkepfgmtpiieakzuxebgxvufmqstzqfufqyccxcetoelmscldmjqnwljacxdtcizgizmyshdhertjakpqrheewkkkrsbhbucnxzwwqikoivovineocgbicsqgffiqwybinhkvnxwyfnhoqjbpoihctkiafbjtfxaknadnhtwuqddljqjpkttyytvaqmdlilvivtdijpuiezgebidzexmllfxlhmxvqudmlyjdojwkqhsofqyqfnpyohlvdxsljhggderlpgmgogjxgfcsenhvlydemxhldvztlbnivfitqkfuxvnganyqsrpfbpqbeplckgfxjauxbozdzdthayutxetwgikxycyhxvdggvuyvffwmszbtyzwobfptyfkzoxdnvcrinfkpmwgvjfdqwbhykuadujnmuumjqilyuaahrlrjlcgcqicxzwfcoavknnmtqclsbtburjyyvyrvthencnkfqxeaabborgkaahksjquognxstbkyyqqlnsxnfptordrrljkpdjdanwpczqmcoqhjskblsbnokoefcynoaxclcmdnpqheuoxozgcvkzeplsxdbdviilmrehmnjrnvvsrfdoxfptwybjrewmfevwtneipvdglozvclgfprvvpjtlynhcydwprjcpqmwntgqhwmikoqzivycchuqgpdgnvuhwyrlriavumziclxqabaupfbvflfqncfdfhvrcwewqjannbenvghsbncfblapizbpauweksrhxidrljzgbtzdyfpfusylaskglybplkiroaagksgrlqdnltvmunisvlnuznkgqhipuwyezfpwymefxmudsjnbflrodwldogksulvfhcgtvlbttkifaamoqatyjcxedekuhkbhjacwnxuuigfimkiovifvmsealaddreqolyuykibwnpsgqonhgfmifogndhdkixoqhazmxfijsvwrllllzkjkrbsvuvlzoclggnvvctkcswopulcvhhvneotwrtnxytbsmekcppfzhhnoyifvchjabdfzijurxuzusvpjxcqxvrtxtcjqmlpssxtohczxqdkjxhpxrkaljirlmxozorabvpxllofmxdpdyzacztzhtvjxhkqkhuprmjliaednyovblreckzxsokdhyhiwwmzayftafpcgojntlhcthylaxivbftctpsynvcqnscvbqleohqjcxwxmyjobwovtxtcpoqrnqsrqkvkjlsiymhavxbeefschseouksdapdzshzogiedbxyrskseprqhktsfiicisdpgnscyqwfritdwsjecfdwzngazabphuslcunydnvtrdfbdxptwyhodnfxyrkxqjdhsgaiczhsjdcuqpgombsooosvwmevhvzyljwtaicdvssxqvigtqzjrkckongviugufmybohuuvmiypcjkpihgvpnuzbpjqhhlwsvgfhhzknbmkfredcjcxiomundowewbuiqzsqkignsdfjbsjsmshfasvdvnssyncrtukeidevotgqefvwnwonbpimknzirqozmhrprekhhaautuqcqrxfjybwdegjgwmdaxeihxiktucouxbjsjzymvxiilhmdevrxjdzaiqhvziexytgxzroqztccrpxaxsqmycfchmwfqnomfnzephffcuvfvchpxjnyfasrhporwbdwpklxmaueddraelutbgpoakzmxjljjvkdybsppqdovefuthpnstdvecidyfmcbyjlylglkkokiwiajcrjamhmlvqmvufodvymqhijldguwwgplvamerrvmqvhdoakryfprvhgzrkbbveghpgqdrpkvbvzxvcfqdaipoijjmpvnxmpykijwdkrimlscjvpocohyqdglomlsnkzyelegqsjtigavssxqyknqswputqpzjgpkqgqhopqpvebmgsmsqzitsfyoptrggikmexlwtehniszvhjxvnisrkvdootdlizhbajxgnqajwssjjcetaouodvrelaymyzdavwbfvxivkqmtkzmqvayzvjqowtbcpmlarjeldqjyfgxtgvavccdasxmomxrtefhyrjlnfosrylxkdowrpibkmrtfgeqoukgutgsyvtlpzlrchpeqlwyfbqyocmitgqljxiwkofhqntsktxbgnucpzkunhgaufpodswjraylzsmwbizlwcomhqodsrcxqmstfbbrxqbqqhqmftdvnmcfvjvwzjyhtrvnvvqlcbduwvzxearikfehvnzpyzosfzyoiznakhrdvdoykigustfnifnivwmsmgadeqlnbyddwvcnlnyoaaiqunxpgrpdrfognvnldfvtssujscurwexfotfywaejxillzulexyruvaucvtmanbeikevrlsovupkkopahwuvqibixgpufmhkoeztwbekvpqwrpfidmuiitpsrjbgalppvkrbqaqnftlhftxbibkpyoainpesvzittngyrmfmoxbiadwseyuoiccqtovackhtwuibhqapieoeyitfqhtoiatzrcekdprqugbxdtrynhqlqzayoebnbnxhgbofmccuewuasosctbsjqtatuyomywqqvikyruziblmpnlqgqwcvhcxvodmoimbzxdyjpnhgfvuizaaknyjbfgahemhxzklkvzizxkjvgxbuxdsepvssybyuyykfttdopdtfoensabuyutqrxilbzfzifapziikwayazifmzextuvuiuukyjmidykguwphzxyyyyluranfzxvitperuozqxehexpwzmlrzmvwgvvpfnhpeayevheufvrnrhtwnjmlyujoheqrmxftujrasvfakoojpglgpxpzqhytmwiwccbdbttsekrvvinhjbhkathmjnnxfjsdgrcvqoureedvjjeqjyobfbqvlrqmmrummkiwutteszpugtugqdazbxwbcgofabithxjryfvnmmogccjweyjgnkebdgtbpqvqrxxbbaerfiiihzxmxhynggamgldsswelhjtklaxfwoewqubbcmfsddcqstijynwzkqfucsupwxenxmjvajronvgnwskrsrosuzatvnjqmuehhnabbgevqukbtkytaddwyimkrmjvgcvgxmtfraqydimrxpqqbjaoaoqtyqdxdivvfaspqsikjbwqxwewpszplkoqoguzlsiqirnhefmekrucjmquxyldsjsjsooqrmlzkvjhjjobovwmadkfplacnogdlpuwyxboczemnsnicecugtbcdcmvktuybwelovezrsafnwytneimwwufuzxaxajwrjmhglyogioplrrttykcybzregvilxoppuiidufnhimbbrgqxlftwrxmlkwqfrzkzhlchcwydcyrtugvivyyxgaphiaikrdzrvosctwlyeuhrbkoalqktmsigzegsoneyzpwbxlwhdktehweretjjzkxpwwgofzcdaknekstvuyzlbamufvoeaqnvtxnegvvryklkcluprgbbqhbcboyaghssrickpetnzyerurivxfbwztoxinbzoekgnfafctkruexdysdvzwdmhnqglljqgssihwauocckzjxgtbxunlobroaxnzrzkxyaxfyeuwroihrspzrbyzaeyxbqgnxdiqnubjunqxsypdmgxmzrtfgrzgausoulxrkmagawbvoyxozukstyegnmxwenwdiwtlfjbbrtiebjessxsyzctzvigevscuxordevpuwajfkvdvsrnprlsusyecqezgcjgatvfyrlzknljkrxwueyjdawuzxeutnzowzqlqreoinpkvayuuzsqkjojpprypypivntdewmefivfkcctyqbecnppoouevkpcmwfqkztlfpeuhhblyfashfpkdrvhusqgpnettddkqpdwxhvndlibdkyqxgixhrotymglquldzjagnsemeofwanneyzjsaobakmftxxcmprahqovswdfkfzjyccdoafpllaxvgsccpnasakdaswttjqwmcauyzohjxmryxcvlmmhvsgrgsbpolgbmsaoxdfhsntmyelyxlibaofwlnqzchrydjiylbldwcmhponujcujcfpznbhbexlpniteybzsvbigeqqufrbkttunbbufjhzwjchedgpryzbngvcpctbfmpivxokbgqyiazrwwcuuifhoyazyugqjnizzcjkenzgcrzlxvblrphkmpjlujknhgffgvdpclbzdoohdjbngessfrvucjttdtsgyhovhmetnouwdotscqwpmrjxdobnxxkzxoqhnfopjganfutirrzofkswidmbztagzrtahmyeveqfekwvrppjdbkpemswbswhffvcroqooupxxaiejxwieuvdyrlnnslvgrvmxkpqddiaxyapdlszfamjxqwsbndswfwcqfmorzmrebjiyvptaexxfkxaijfjazrfbtrtqqoxwlhifdytiqeysvuqwddeskrszdlzcnqxxtcmcjplixwiyukwdufwtafwzfewlfazmzlgnfthgvkmtcukhjgrmxfxregxuwefwftajqmrqigqurzixgosnnsywdqwmezopwcjwmatyrgdbyqhxadlfdutdocpnrphskzqfpusytrkgriwivvptfdchsatvzlhdrlwfjsnyqhcqnusmvqoquajxsyzijvioylpeftpwfnontivxahjerzxrqznqemadfzbhbdqzthefzvthslfgojveuggcsvszuftxnlmkerplqpewqfapqglxihcyjrlwewiuuxlbwyjpqvqlcwhoqtwaksqrmjtkywxamdmpjqjrbswysxjpwgagxlwldkwxdsjyeajiikkkleyamyjoekngiiagivnguhipocssbojaqlcpszqiluowjumaxblpynzdvisfugthcookquhonmmzmczyblawhahnehxlwpjvvqggjmnrjostirlghiwnllirbbkufzifpktuacufedlqunlkxuvkwqnrhkvchucklbyyjezywmefpddgnnyequwyrzxsthktrlmqbintcvmqgjbkivsaxekbwexoeetigulqbcbcfqslvbihgldodanarsuxqzafwohdpplsrhqgserlmgdlhdvoldpjebpmntntzhqylrwrsbuzotvgoriyeizrxqinridgmsxkucxzaxeuasiouwzerzhlbiadcnyezwrijczdmyvpwkdcrefirejlglrznrpxcohzeixqtslvgeodruiswbhcmfgxmoqnibvcdaqcdgvsczpzosryreruykfvhgdzjnlbktykjsizzlefibnbgpvdcabhvrkklrqifhpyqlgcapzucdaaivuvmxzsstniglduhjmhfskzfsbeuyrzssfdpzomrfmjkgpfbxewfivozwuvjlmouvesvulomvpxbelltibjjtjivvllckkggznfkoclpioxszhqsdnzsbpwvyrmdinfglvxspbscikxvnckpnkddfntvvtfsmoazegtghmdepzsmrcuwfdjvvgglvnnioisostwdpwpbmwacvdsrhzkgmkucyvtwqpzkymrdfgnftnretnfdqaxraptdsdxeqlwckioftpbnayftshcatsdzvmbkgjwsvjjpryfdksugkserhhbqvsqimlddnupottavxswddrwymdohqbovbdirriknphsfypfxfqtmltvlbudgnwrlcazxyhmaxzgppvqrtiprfewahsshivfbhajgarypfubgjhdziztuycyatjwfrrdhghehthojwhzeazabqifjkgnnvbfaaabfvzfrkijblzqffnsdqdaqpjnnvrriyzpkemfqvvabfalsyvcdqaylbthsgavonvimxacmxglhjnqefxigmrgpgzgjilhjulsogvseghudqestikxkkntwucrjascfiggokppjxygqxrvahrflkioawiqnalkpivrqhdqavuowifhvwcfgmvstlfmgyzghyfolzwxkfgiybmogiylbrdfrwbasvbxlbfgqjrmfmshepknyivkowbegcukputarpexpdbmexlugdusgnpzgkauqmawumpwfoqksjjkbfdcbnwpkialidsetsciyeazxcdfccibvjlcncnecdhlpkfwavbbimoejjuiysyasuhryuepfrhpgbxuhkrabnhpmovkhdjufdmidbaljhwrafdfpbjewtpvagtfkfikxgwblpvkebhbgnzvcugjiwyhrjextlaeilieqvurtreuwdmnvawascasyzqcmjjiwuznwbdlmkpmbolvrrfdrhmdnhydwcwbzhqiydqmitxlfhekqqjpgkpzmwyywncprfxmfyufeyiuvpojktbtbccwdgwjtruhxjqeyzggqurgbmnwcifdkydzufhqcedtpiwqcofqdncfjwiogugobntaqqnjprcugowukwdgfahdiwbwatwvhffcenntrqojouyqzgaeydawdeudklwwtlnstoanlannuqdcqiwezermdimizcikxbtnqposahnnykmksbjustfaeebrmdpaymcsecozsxsqufsezcvaukmpxhpponxabwnltlwccbconrzfpzyfrgruhvwcskflgdwwqzspnltuskekhfyfqajtkfqwisvqnoauoncxyfxxrlmzzxsnjeecpjhbxcfxglkgxylnfptgmylvkmcvuoqnmsibaokqqbgzplgrlqnzpkaayqiiyszbuegquttkvhtbrmbqegypataonkcdcbeijkmhnrvaahzrvecyjscsdofkreeimwtnmgkfiagwgohqerjkrovxyvumiynpoljkeuaxsdnyidhqsdrlfnzdctwmeupaexmayytmjfonzmcmnewkbrlmyixjgkdosqoltyasxqgrecakmkvbubmrvupwbiuuafgtpozrhtkrlmxyrvmqvzekaakpqnmlqkuvzwzbdfwejbewkuaaajiyozvevmwvmwermsquangtdqybecktonyemmwsfaazgqefffcqzxvtvznntvygcimxzfrvnyussjcclkfuysffwpyngcwruwpwagxeulmvwdnfbkavwkefpgvfvdtcxkirqgxiphqajwmaujuzaetmtgioftilolveobohgauueblpzmhocbdmfxodjqtwopcgaslcbrxqmrtorewgufirabtnsliiopapanjfdpmpspshrbhksbwbacbumxdvfwelfdllvqbrhvsnwiojbsmfwwdzwdefvwpwmiknxmbrdjoabmldsardbqfkytegqlxlkxrppdaxulxrdowpbtzcspeloewlgggvjhsjrzwqoaodidmlvzrgkfapxnjxxqzmekkeeasjkrsqqlxteswliutotsuyfpsxhxiapxfewksfhvajlavyzxmealarvollyqcsomsrezxwwlzqgfmftlevllouyofuizvmbmkapgbjskcwhqngatmamwclvnhfmbevtkagfqjjzkvlqugkdjuityppadiumwlqwdrxukmpftpuaphddpdjxvdxaknomztezmpfhwdaqheuyrlbmbwtzhjtmnsdsrizmynopgkcnudmrqntmqqokjpfdztfekqhhirolqrottmscuxrodurvbighxnoymdgqextmzjweeigywsvkbwzfbluorfzgckxakavrjbwixljenexsazytnhubgnprszevjycwesnfnirajntmdepflgapwwxkkludufamlhrafpopzgsgroihdxxqbgljjzpzavfqxhswnjafbturgxnfhxqilsdwgkdurplkzxtidzxoxpjbdkxnofdbcjkssuoajjaembbszujtnalfglfdbeyulmqbrccabxvrompwfmmqdhcwbjivmyfrkxivsrcdgygcvnwbgqpzzscxchfqtkhxgqfybjbkwcorchgcbqvbqiklolfwppmqowqtslzvuoqquweepfqiuvvzxrqvbsjqyuwexsomvxgzuwgxqhyjkhaowzcrczmqqxthknzyvlknmxsaqreeejetyexynbhxtpdwacvgqevnadhqgaichvswoylhschxwehhokboqlehlwpuzrqcvdmzwqargmhqohnbpgipxkdmtspmyyulxpyvcusjdyutdhxadprevwpkzdxxquezlkbersewcxfikvpnikptrvsnscnnpcfcdpgluyrcqdoinnggekcstgfumcvkpczluakurbihrwnkxxbzzgpxvvgfzxqyffdzlgsakuyyqyknbepiecccjfjtqnpzdnajcgkvhewbhzqdvleycpcwftslutldilocyxfhxhunmutbesfhxvycasuljhfzvmkplnoppzbrxjsxxajzuwnqbcsfjwyqaisrgxyukjgroohazxbfzelnpnbbsdabjjxbiocukmfafilwumzoztgnkqfdtbcfqjuuiyrkfpqblwiiotxwwqdzczjomuirhngzuivhhjyynaimuzukfoepzeodqqurcfcybygkalrcowcwtgiejbgotacgpecmmowkenyfcrqunxdaqgwgfhzjdcmkwknhuxaghjsocczlvvewfdkyzwgdbhrozabrzsuzqoluljghunwjwsmgtfsyltjsibbijccazheiuqfzaahylqpvxcxfaxkqflatrztawsysuuqjgalfklawuxlbfobgtuwpvrmaifqmlptznjffcshrgouifxeqvxfkkgtiftbymhaaqkyqlqxgdfydswgmzvosvtwdgljptjcerpewclilmrqaaozvzbynhiojvyqdvpadtavejcqyioeqrhrbmgylgxcnqnrjgaceoguvldpswrltauoyorjzfjuvrxaoxlqkdpaobjvpmaslycioyzyorhimamzxqfbeqapozusxfqmkodomekxsuetbbubfsiuztgyekxwseqowxlaykqrziemqnovygkynjgkkapvpxyjxtarcamrdhyxvqasdhacctgwszjumswoauyjgfjdgdszvsokrtfytvonfssrbbisulqncihosrrrttcbdnvlbdadrbpjjymuaoskwuwgsanczjmjgwrhpvobchrumtxbvbetslwngawyvbadwpzmelqlphkyzffnwylsnqwnlofppdajlyqxhkxhwzdgqiuzympostmndgfzzoognoczxevscekhdjcahkrezafplvqeearfpymmzixsjnyvnxiwjiahjdgvfwebmbdbhmnuzarpsmpirasccwfgtanfwiogryzwfcyfghfhwpdxjdzzteycrixvxfurpyojvaackjofrheqgsoavuskxaedkstbrodwybvrtnzgvtbeeanfqamhijugvvnwyockzlxaguoewmriytdncpwjmxtzpcoqqrejsahxkkqjqxykmprwzxrrszziqceljedhiptzosgfulcatmfvikpvemkwjpwcoiljjntzdrtgzakiiuhbmvixbcotfukiuectnahuhjgxjsntgtvzigdueoaxeyluqimpribqlapakrwgfwlablzphjqxlictbdnrjfmmihklllqobmvihjsrnhlsowxdyatfsyykckdernffhxkwhqobcprymqbfrfxaazyyrqzrbovywftmdckamomsxvhghicnopmggaiibxirjgcftgkemcioneqlwezorunueudyhkgowopssxiacawzovuoffkaetjiosordmccdgxwlnxoihqwnvkbmooeibdkktbzvlexhklkdeynlyvxvdymozlkpgnhniypvogvwofwnftwwlfcwnccwuommziyzayrghupervboixapyluoslsmlrlvuxadoarzxaygdldllbinhysjnkgtxzbluohirbijdczjibhymwgjqrifgwvrqzsbntjymfcmmzplscsjfbsoumymwyzuztnztbkvshyztmwipdhnxpsbeastxrspqllnpdsggqgteccwcahdnkzkphawyzrrhvlzqyhabfegrpucevtrksvevjmcfnyvtuaequwwueywlxvkggvjxfnzbxmetcvdxiavdflzedslyyofjgsyjgnynvybkegugbyjhuwpflijhfzddfpnnysznctxhrtftwzksudkrkpkyasmtcvsmqnxtamaaaucpeqvvimvpyhmfndtvaxnbrruimzncyuvvojasggedotbrhqwhsggbnaachnoowtvqlnvizqfeoffxrrtzradahxsvwncwcpmevktmbqgkvcekoxhwvgtjxeiuzbqjvrxnsljyte");
    return 0;
}
